### ISSUE TITLE
想向您请教一个问题

### ISSUE THREAD

**Issue by wxg123456** [Xinhai-Li/2019-nCoV#1]
请问您的这个代码是用什么软件运行的呢

**Comment by Xinhai-Li** [comment]
R语言

 

From: noreply@github.com [mailto:noreply@github.com] On Behalf Of wxg123456
Sent: Sunday, May 10, 2020 9:24 PM
To: Xinhai-Li/2019-nCoV <2019-nCoV@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [Xinhai-Li/2019-nCoV] 想向您请教一个问题 (#1)

 

请问您的这个代码是用什么软件运行的呢

**Comment by wxg123456** [comment]
谢谢
